apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    pv: nfs-kunkun
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.21
    path: "/data/"
