apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      pv: nfs-kunkun
  resources:
    requests:
      storage: 1Gi
